#!/usr/bin/env bash
set -euo pipefail
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/deploy-functions

# try to use .git/ref if APP_VERSION is not set
[ -z "${APP_VERSION:-}" ] && [ -f .git/ref ] && APP_VERSION="$(cat .git/ref)"

require_env_vars "ARTIFACTORY_USERNAME" "ARTIFACTORY_PASSWORD" "MARKLOGIC_HOST" "APP_NAME" "APP_VERSION" "ML_MODULES_VERSION"

declare local_zip="/tmp/ml-modules-${ML_MODULES_VERSION}.zip"

fetch_ml_modules "${ML_MODULES_VERSION}" "${ARTIFACTORY_USERNAME}:${ARTIFACTORY_PASSWORD}" "${local_zip}"

deploy_to_marklogic "${MARKLOGIC_HOST}" "${APP_NAME}" "${APP_VERSION}" "${local_zip}"
