#!/usr/bin/env bash
set -euo pipefail
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/deploy-functions

if [[ "${USE_BUILD_VERSION:-}" == "true" ]]; then
  APP_VERSION="${BUILD_VERSION}"
else
  APP_VERSION="${APP_VERSION:-$GIT_REVISION}"
fi

require_env_vars "MARKLOGIC_HOST" "APP_NAME" "APP_VERSION" "DEPLOY_ZIP"

deploy_to_marklogic "${MARKLOGIC_HOST}" "${APP_NAME}" "${APP_VERSION}" "${DEPLOY_ZIP}"
