#!/usr/bin/env bash
set -euo pipefail
source ./deploy-functions

require_env_vars "MARKLOGIC_HOST" "APP_NAME" "APP_VERSION" "DEPLOY_ZIP"

deploy_to_marklogic "${MARKLOGIC_HOST}" "${APP_NAME}" "${APP_VERSION}" "${DEPLOY_ZIP}"
