#!/usr/bin/env bash
set -euo pipefail
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/deploy-functions

if [[ "${USE_BUILD_VERSION:-}" == "true" ]]; then
  APP_VERSION="${BUILD_VERSION}"
else
  APP_VERSION="${APP_VERSION:-$GIT_REVISION}"
fi

require_env_vars "ARTIFACTORY_USERNAME" "ARTIFACTORY_PASSWORD" "MARKLOGIC_HOST" "APP_NAME" "APP_VERSION" "ML_MODULES_VERSION"

declare local_zip="/tmp/ml-modules-${ML_MODULES_VERSION}.zip"

fetch_ml_modules "${ML_MODULES_VERSION}" "${ARTIFACTORY_USERNAME}:${ARTIFACTORY_PASSWORD}" "${local_zip}"

deploy_to_marklogic "${MARKLOGIC_HOST}" "${APP_NAME}" "${APP_VERSION}" "${local_zip}"
