#!/usr/bin/env bash
set -euo pipefail
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/deploy-functions

# try to use GIT_REVISION if APP_VERSION is not set
APP_VERSION="${APP_VERSION:-$GIT_REVISION}"

require_env_vars "MARKLOGIC_HOST" "APP_NAME" "APP_VERSION" "DEPLOY_ZIP"

deploy_to_marklogic "${MARKLOGIC_HOST}" "${APP_NAME}" "${APP_VERSION}" "${DEPLOY_ZIP}"
